### ISSUE TITLE
TRASH

### ISSUE THREAD

**Issue by kranercc** [mac-cleanup/mac-cleanup-sh#112]
this piece of shit code fucked over my links with code Xcode and all other similar development links

deleted a ton of useful stuff

# REMOVE THIS FROM GITHUB idiot shit

**Comment by Drugsosos** [comment]
Hey, can you elaborate on the problem you faced?
I'm sorry you had a bad experience, but it would be appropriated if you'll leave more details

**Comment by kranercc** [comment]
you are a total idiot fuck you for ruining my dev enviroment

**Comment by Drugsosos** [comment]
I understand your frustration but GitHub isn't the place to behave like this and you could get a ban(

So can you change your attitude and elaborate? I really don't want you to get in trouble and other people to face the same problem you have had

**Comment by fwartner** [comment]
Since this is open source, you could easily watch the code and see whats happening under the hood.
